### ISSUE TITLE
Missed dependency

### ISSUE THREAD

**Issue by p00h** [Hains/openpli-dm8000-oe-core#1]
I've just got an error trying to make the image. The lazka/mutagen repo is no longer available at bitbucket.org.
`ERROR: python-mutagen-1.34.1-r1 do_fetch: Fetcher failure for URL: 'https://bitbucket.org/lazka/mutagen/downloads/mutagen-1.34.1.tar.gz'. Unable to fetch URL from any source.`

**Comment by p00h** [comment]
https://github.com/Hains/openpli-dm8000-oe-core/pull/2

**Comment by Hains** [comment]
Thanks.. I also update version to 1.38.
