### ISSUE TITLE
No tuners found

### ISSUE THREAD

**Issue by p00h** [Hains/openpli-dm8000-oe-core#3]
I've just built and installed the image.
After that, i had tried to look for providers and channels, but no suitable tuners were found.
```
root@dm8000:~# uname -a
Linux dm8000 3.2-dm8000 #1 SMP Wed Aug 23 12:52:25 +05 2017 mips GNU/Linux
root@dm8000:~# lspci
00:01.0 Class 0200: 168c:001a
01:00.0 Class 0101: 14e4:8602
root@dm8000:~# lsusb
Bus 001 Device 001: ID 1d6b:0002
Bus 002 Device 001: ID 1d6b:0002
Bus 003 Device 001: ID 1d6b:0001
Bus 004 Device 001: ID 1d6b:0001
Bus 001 Device 002: ID 04cc:1520
Bus 001 Device 003: ID 058f:6362
```
What've i missed?

**Comment by Hains** [comment]
I don't use usb tuners myself. internal dvb-s2 and dvb-c tuners works fine.
For USB tuners you probably miss kernel-module/driver  depending on brand chipset.

**Comment by p00h** [comment]
Ok, it seems the driver for my box wasn't installed

**Comment by p00h** [comment]
I've completely stuck on that. Could you please telnet to your box and post `lsusb` and `lspci` outputs here?

**Comment by Hains** [comment]
root@dm8000:~# lsusb
Bus 001 Device 001: ID 1d6b:0002
Bus 002 Device 001: ID 1d6b:0002
Bus 003 Device 001: ID 1d6b:0001
Bus 004 Device 001: ID 1d6b:0001
Bus 001 Device 002: ID 04cc:1520
Bus 001 Device 003: ID 058f:6362
root@dm8000:~# lspci
00:01.0 Class 0200: 168c:001a
01:00.0 Class 0101: 14e4:8602
root@dm8000:~#

**Comment by p00h** [comment]
Thank you
