### ISSUE TITLE
Build failed (Makefile:452: recipe for target 'testlk-testlk.o' failed)

### ISSUE THREAD

**Issue by DutchDude69** [Hains/openpli-dm8000-oe-core#5]
For some reason the build is failing. (Was building fine before)
And i can't figure it out :-(
Could you maybe give me some pointers to look for? 

Kind regards,
Menno

gcc: error: unrecognized command line option â€˜-fmacro-prefix-map=/home/apple/openpli-dm8000-oe-core/build/tmp/work/mips32el-oe-linux/nfs-utils/2.3.3-r0=/usr/src/debug/nfs-utils/2.3.3-r0â€™
Makefile:452: recipe for target 'testlk-testlk.o' failed
make[2]: *** [testlk-testlk.o] Error 1
make[2]: Leaving directory '/home/apple/openpli-dm8000-oe-core/build/tmp/work/mips32el-oe-linux/nfs-utils/2.3.3-r0/nfs-utils-2.3.3/tools/locktest'
Makefile:417: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/apple/openpli-dm8000-oe-core/build/tmp/work/mips32el-oe-linux/nfs-utils/2.3.3-r0/nfs-utils-2.3.3/tools'
ERROR: oe_runmake failed
Makefile:456: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1
WARNING: /home/apple/openpli-dm8000-oe-core/build/tmp/work/mips32el-oe-linux/nfs-utils/2.3.3-r0/temp/run.do_compile.1635:1 exit 1 from 'exit 1'
ERROR: Function failed: do_compile (log file is located at /home/apple/openpli-dm8000-oe-core/build/tmp/work/mips32el-oe-linux/nfs-utils/2.3.3-r0/temp/log.do_compile.1635)

[log.do_compile.1635.log](https://github.com/Hains/openpli-dm8000-oe-core/files/2973749/log.do_compile.1635.log)

**Comment by Hains** [comment]
Try to revert commit:
https://github.com/Hains/openpli-dm8000-oe-core/commit/1759348f18e3f02b58cc70ef250b395fddf898fd

This was the first commit to fix build.
https://github.com/Hains/openpli-dm8000-oe-core/commit/0edf409d8d6597d2528280fc6453770f217baf85

**Comment by DutchDude69** [comment]
Thanks, that did the trick.
I forked your repo, did a revert on [1759348](https://github.com/Hains/openpli-dm8000-oe-core/commit/1759348f18e3f02b58cc70ef250b395fddf898fd) and the build finished fine. 

Thanks for your help!
👍

**Comment by DutchDude69** [comment]
Faced one more issue ;-)
The image builds ok after the revert. But the building of the feed is failing when making "astra-sm"
Looks like there where no recent changes done on it?
Maybe some more pointers to try ;-)

Kind regards,
Menno
[log.do_compile.13740.log](https://github.com/Hains/openpli-dm8000-oe-core/files/2986965/log.do_compile.13740.log)

**Comment by Hains** [comment]
What OS do you use, Ubuntu, Archlinux?

**Comment by DutchDude69** [comment]
Hi,

I build on Ubuntu 17.04.

**Comment by Hains** [comment]
That must be the problem, since it builds fine for me with Ubuntu 18.10.

Can you upgrade to Ubuntu 18.04.x LTS (should be no problem as well)?
Also to prevent future build failures.

**Comment by Hains** [comment]
Update:
Oh..You edited your post.
You're on Ubuntu 18.04 already and not on 17.04.

**Comment by DutchDude69** [comment]
After you asking me what OS i was running, i thought maybe i need to upgrade.
So i upgraded to 18.04.2 LTS today and started with a fresh build.
But the feed building still stops with the same error as before. The image builds fine.

**Comment by DutchDude69** [comment]
As mentioned after upgrading to 18.04 LTS i still had build problems, and even when i upgraded once more to 18.10 the same build failures where seen. So before i decided to wipe the machine and start from scratch, i upgraded to Ubuntu Dev version 19.04. And this made the difference. The image and feed are now building fine, without the need of reverting any commit. :-)
