### ISSUE TITLE
libdca_0.0.6.bb

### ISSUE THREAD

**Issue by zwoar** [Hains/openpli-dm8000-oe-core#6]
change line 10 in libca_0.0.6.bb
- SRC_URI = "https://mirror.nl.leaseweb.net/videolan/libdca/${PV}/libdca-${PV}.tar.bz2"
+ SRC_URI = "http://download.videolan.org/pub/videolan/libdca/0.0.6/libdca-${PV}.tar.bz2"

**Comment by Hains** [comment]
Done, thanks.
